"""Write a :class:`~vibemol.model.structure.Structure` to PDB text.

The inverse of the fixed-column reader in :mod:`vibemol.io.pdb`; emits ATOM /
HETATM records (current coordinates) plus CONECT records for inferred bonds.
"""

from __future__ import annotations

from ..model.structure import Structure


def _atom_name_field(name: str) -> str:
    """Place the atom name in cols 13-16 per PDB convention (4-char names flush)."""
    return name[:4] if len(name) >= 4 else f" {name:<3}"


def write_pdb(structure: Structure) -> str:
    s = structure
    lines = ["REMARK   Generated by VibeMol"]
    for i in range(s.n_atoms):
        record = "HETATM" if bool(s.is_hetatm[i]) else "ATOM  "
        serial = (i % 99999) + 1
        x, y, z = (float(c) for c in s.coords[i])
        line = (
            f"{record}{serial:>5} {_atom_name_field(s.atom_names[i]):<4} "
            f"{s.res_names[i]:>3} {s.chain_ids[i][:1] or 'A':1}{int(s.res_ids[i]):>4}    "
            f"{x:8.3f}{y:8.3f}{z:8.3f}{float(s.occupancies[i]):6.2f}{float(s.b_factors[i]):6.2f}"
            f"          {s.elements[i]:>2}"
        )
        lines.append(line)
    # CONECT records (1-based serials) for the inferred/explicit bonds.
    for a, b in s.bonds:
        lines.append(f"CONECT{int(a) + 1:>5}{int(b) + 1:>5}")
    lines.append("END")
    return "\n".join(lines) + "\n"
